apiVersion: v1
kind: ServiceAccount
metadata:
  name: coolstore-inventory-service
  labels:
    app.kubernetes.io/name: coolstore-inventory-service
    app.kubernetes.io/component: inventory
    app.kubernetes.io/part-of: coolstore
